class Question {
  final int id, answer;
  final String question;
  final List<String> options;
  final String difficulty;

  Question({
    required this.id,
    required this.question,
    required this.answer,
    required this.options,
    required this.difficulty,
  });
}

const List sample_data = [
  // EASY LEVEL QUESTIONS
  {
    "id": 1,
    "question": "Flutter is an open-source UI software development kit created by ______",
    "options": ['Apple', 'Google', 'Facebook', 'Microsoft'],
    "answer_index": 1,
    "difficulty": "Easy",
  },
  {
    "id": 2,
    "question": "What programming language is Flutter primarily written in?",
    "options": ['Java', 'Kotlin', 'Dart', 'Swift'],
    "answer_index": 2,
    "difficulty": "Easy",
  },
  {
    "id": 3,
    "question": "Which widget is used to create a scrollable list in Flutter?",
    "options": ['Column', 'Row', 'ListView', 'Stack'],
    "answer_index": 2,
    "difficulty": "Easy",
  },
  {
    "id": 4,
    "question": "What does HTML stand for?",
    "options": ['Hyper Text Markup Language', 'High Tech Modern Language', 'Home Tool Markup Language', 'Hyperlinks and Text Markup Language'],
    "answer_index": 0,
    "difficulty": "Easy",
  },
  {
    "id": 5,
    "question": "Which keyword is used to declare a variable in Dart?",
    "options": ['let', 'var', 'const', 'Both var and const'],
    "answer_index": 3,
    "difficulty": "Easy",
  },
  {
    "id": 6,
    "question": "What is the correct file extension for Python files?",
    "options": ['.pyth', '.pt', '.py', '.pyt'],
    "answer_index": 2,
    "difficulty": "Easy",
  },
  {
    "id": 7,
    "question": "Which symbol is used for single-line comments in JavaScript?",
    "options": ['//', '#', '/*', '--'],
    "answer_index": 0,
    "difficulty": "Easy",
  },
  {
    "id": 8,
    "question": "What does CSS stand for?",
    "options": ['Computer Style Sheets', 'Cascading Style Sheets', 'Creative Style Sheets', 'Colorful Style Sheets'],
    "answer_index": 1,
    "difficulty": "Easy",
  },
  {
    "id": 9,
    "question": "Which widget is the base class for all stateless widgets in Flutter?",
    "options": ['Widget', 'StatelessWidget', 'BaseWidget', 'FlutterWidget'],
    "answer_index": 1,
    "difficulty": "Easy",
  },
  {
    "id": 10,
    "question": "What is the main function of a compiler?",
    "options": ['Execute code', 'Translate code to machine language', 'Debug code', 'Format code'],
    "answer_index": 1,
    "difficulty": "Easy",
  },
  {
    "id": 11,
    "question": "Which data type is used to store true or false values?",
    "options": ['int', 'String', 'bool', 'double'],
    "answer_index": 2,
    "difficulty": "Easy",
  },
  {
    "id": 12,
    "question": "What does API stand for?",
    "options": ['Application Programming Interface', 'Advanced Programming Interface', 'Application Process Integration', 'Automated Programming Interface'],
    "answer_index": 0,
    "difficulty": "Easy",
  },
  {
    "id": 13,
    "question": "Which loop is guaranteed to execute at least once?",
    "options": ['for loop', 'while loop', 'do-while loop', 'foreach loop'],
    "answer_index": 2,
    "difficulty": "Easy",
  },
  {
    "id": 14,
    "question": "What is the default value of an uninitialized boolean variable in Dart?",
    "options": ['true', 'false', 'null', '0'],
    "answer_index": 2,
    "difficulty": "Easy",
  },
  {
    "id": 15,
    "question": "Which widget is used to add padding around a child widget in Flutter?",
    "options": ['Margin', 'Padding', 'Container', 'SizedBox'],
    "answer_index": 1,
    "difficulty": "Easy",
  },

  // MEDIUM LEVEL QUESTIONS
  {
    "id": 16,
    "question": "What is the purpose of the setState() method in Flutter?",
    "options": ['To create a new state', 'To notify the framework that state has changed', 'To delete the current state', 'To initialize state'],
    "answer_index": 1,
    "difficulty": "Medium",
  },
  {
    "id": 17,
    "question": "Which design pattern is commonly used for state management in Flutter?",
    "options": ['Singleton', 'Factory', 'BLoC', 'Prototype'],
    "answer_index": 2,
    "difficulty": "Medium",
  },
  {
    "id": 18,
    "question": "What is the difference between hot reload and hot restart in Flutter?",
    "options": ['No difference', 'Hot reload preserves state, hot restart does not', 'Hot restart is faster', 'Hot reload requires rebuilding'],
    "answer_index": 1,
    "difficulty": "Medium",
  },
  {
    "id": 19,
    "question": "What is the purpose of the async keyword in Dart?",
    "options": ['To make code run faster', 'To mark a function as asynchronous', 'To handle errors', 'To create threads'],
    "answer_index": 1,
    "difficulty": "Medium",
  },
  {
    "id": 20,
    "question": "Which lifecycle method is called when a StatefulWidget is removed from the widget tree?",
    "options": ['initState()', 'build()', 'dispose()', 'deactivate()'],
    "answer_index": 2,
    "difficulty": "Medium",
  },
  {
    "id": 21,
    "question": "What is the purpose of the Future class in Dart?",
    "options": ['To represent past values', 'To represent a potential value or error available in the future', 'To create timers', 'To manage memory'],
    "answer_index": 1,
    "difficulty": "Medium",
  },
  {
    "id": 22,
    "question": "Which HTTP method is used to update existing resources?",
    "options": ['GET', 'POST', 'PUT', 'DELETE'],
    "answer_index": 2,
    "difficulty": "Medium",
  },
  {
    "id": 23,
    "question": "What is the purpose of the BuildContext in Flutter?",
    "options": ['To build widgets', 'To provide location of a widget in the widget tree', 'To manage state', 'To handle events'],
    "answer_index": 1,
    "difficulty": "Medium",
  },
  {
    "id": 24,
    "question": "What does OOP stand for in programming?",
    "options": ['Object Oriented Programming', 'Objective Operational Programming', 'Open Object Programming', 'Organized Operational Programming'],
    "answer_index": 0,
    "difficulty": "Medium",
  },
  {
    "id": 25,
    "question": "Which widget is used to make a widget respond to gestures in Flutter?",
    "options": ['Touchable', 'GestureDetector', 'InkWell', 'Both GestureDetector and InkWell'],
    "answer_index": 3,
    "difficulty": "Medium",
  },
  {
    "id": 26,
    "question": "What is the purpose of the const keyword in Dart?",
    "options": ['To create variables', 'To create compile-time constants', 'To prevent changes', 'To optimize memory'],
    "answer_index": 1,
    "difficulty": "Medium",
  },
  {
    "id": 27,
    "question": "Which method is used to navigate to a new screen in Flutter?",
    "options": ['Navigator.push()', 'Navigator.go()', 'Navigator.move()', 'Navigator.navigate()'],
    "answer_index": 0,
    "difficulty": "Medium",
  },
  {
    "id": 28,
    "question": "What is dependency injection?",
    "options": ['A way to inject bugs', 'A design pattern for providing dependencies to a class', 'A testing framework', 'A database pattern'],
    "answer_index": 1,
    "difficulty": "Medium",
  },
  {
    "id": 29,
    "question": "What is the purpose of the Key class in Flutter?",
    "options": ['To encrypt data', 'To uniquely identify widgets', 'To store values', 'To manage state'],
    "answer_index": 1,
    "difficulty": "Medium",
  },
  {
    "id": 30,
    "question": "Which package is commonly used for HTTP requests in Flutter?",
    "options": ['http', 'dio', 'axios', 'Both http and dio'],
    "answer_index": 3,
    "difficulty": "Medium",
  },

  // HARD LEVEL QUESTIONS
  {
    "id": 31,
    "question": "What is the purpose of the InheritedWidget in Flutter?",
    "options": ['To inherit properties', 'To efficiently propagate data down the widget tree', 'To create parent widgets', 'To manage lifecycle'],
    "answer_index": 1,
    "difficulty": "Hard",
  },
  {
    "id": 32,
    "question": "What is the difference between Isolates and Threads in Dart?",
    "options": ['No difference', 'Isolates have separate memory, threads share memory', 'Threads are faster', 'Isolates are deprecated'],
    "answer_index": 1,
    "difficulty": "Hard",
  },
  {
    "id": 33,
    "question": "What is the purpose of the RepaintBoundary widget?",
    "options": ['To set boundaries', 'To optimize rendering by creating separate layers', 'To prevent repainting', 'To manage memory'],
    "answer_index": 1,
    "difficulty": "Hard",
  },
  {
    "id": 34,
    "question": "Which rendering pipeline stage is responsible for determining the size of widgets?",
    "options": ['Build', 'Layout', 'Paint', 'Composite'],
    "answer_index": 1,
    "difficulty": "Hard",
  },
  {
    "id": 35,
    "question": "What is the purpose of the compute() function in Flutter?",
    "options": ['To perform calculations', 'To run expensive computations in a separate isolate', 'To optimize code', 'To debug performance'],
    "answer_index": 1,
    "difficulty": "Hard",
  },
  {
    "id": 36,
    "question": "What is the difference between ChangeNotifier and ValueNotifier?",
    "options": ['No difference', 'ValueNotifier holds a single value, ChangeNotifier can manage multiple values', 'ChangeNotifier is deprecated', 'ValueNotifier is faster'],
    "answer_index": 1,
    "difficulty": "Hard",
  },
  {
    "id": 37,
    "question": "What is the purpose of the Ticker class in Flutter animations?",
    "options": ['To create timers', 'To provide a callback for each frame', 'To manage animation state', 'To optimize performance'],
    "answer_index": 1,
    "difficulty": "Hard",
  },
  {
    "id": 38,
    "question": "What is tree shaking in Flutter?",
    "options": ['A testing method', 'Removing unused code during compilation', 'A widget animation', 'A debugging tool'],
    "answer_index": 1,
    "difficulty": "Hard",
  },
  {
    "id": 39,
    "question": "What is the purpose of the RenderObject in Flutter?",
    "options": ['To render images', 'To handle the actual rendering and layout logic', 'To create widgets', 'To manage state'],
    "answer_index": 1,
    "difficulty": "Hard",
  },
  {
    "id": 40,
    "question": "What is the difference between SizedBox.expand() and Expanded widget?",
    "options": ['No difference', 'SizedBox.expand fills available space, Expanded fills space in Flex widgets', 'Expanded is deprecated', 'SizedBox.expand is faster'],
    "answer_index": 1,
    "difficulty": "Hard",
  },
  {
    "id": 41,
    "question": "What is the purpose of the Semantics widget?",
    "options": ['To add meaning to code', 'To provide accessibility information to screen readers', 'To optimize performance', 'To manage layout'],
    "answer_index": 1,
    "difficulty": "Hard",
  },
  {
    "id": 42,
    "question": "What is the difference between microtask queue and event queue in Dart?",
    "options": ['No difference', 'Microtask queue has higher priority than event queue', 'Event queue is faster', 'Microtask queue is deprecated'],
    "answer_index": 1,
    "difficulty": "Hard",
  },
  {
    "id": 43,
    "question": "What is the purpose of the CustomPainter class?",
    "options": ['To paint widgets', 'To create custom graphics and drawings', 'To apply colors', 'To manage themes'],
    "answer_index": 1,
    "difficulty": "Hard",
  },
  {
    "id": 44,
    "question": "What is platform channel in Flutter?",
    "options": ['A TV channel', 'A mechanism to communicate between Dart and native code', 'A widget', 'A routing system'],
    "answer_index": 1,
    "difficulty": "Hard",
  },
  {
    "id": 45,
    "question": "What is the purpose of the Zone class in Dart?",
    "options": ['To create zones', 'To handle errors and manage execution context', 'To optimize memory', 'To create threads'],
    "answer_index": 1,
    "difficulty": "Hard",
  },
];